<?php
/**
 * @var \Library\Form\Cart\CreditCardFieldset $pay_info_form
 */
?>
<?php echo $this->formRow($pay_info_form->get('credit_card_csrf')); ?>
<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <?php echo $this->formRow($pay_info_form->get('card_num')); ?>
            <img style="display: block; margin-top: 4px; margin-bottom: 5px;" width="130" src="/img/layout_images/credit_card_logos.png"/>
        </div>
    </div>
    <div class="col-xs-12 form-inline">
        <div class="form-group">
            <?php echo $this->formRow($pay_info_form->get('exp_month')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($pay_info_form->get('exp_year')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($pay_info_form->get('cvc')); ?>
        </div>
    </div>
    <div class="col-xs-12">
        <div style="margin-top: 8px;" class="form-group">
            <button class="card_submit btn btn-success" type="submit">Submit Order <i class="fa fa-arrow-circle-o-right"></i></button>
        </div>
    </div>
    <?php echo $this->formRow($pay_info_form->get('pay_method')); ?>
</div>
