<div class="row">
    <div class="col-md-4">
        <?php echo $this->print_content_block('contact_page_address'); ?>
    </div>
    <div class="col-md-8">
        <h1>Contact Us</h1>
        <form method="post">
            <input type="hidden" name="task" value="contact"/>
            <div class="form-group">
                <input type="text" placeholder="Email" name="email" class="form-control"/>
            </div>
            <div class="form-group">
                <input type="text" placeholder="Subject" name="subject" class="form-control"/>
            </div>
            <div class="form-group">
                <textarea placeholder="Content" style="height: 215px;" name="content" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-success"><i class="fa fa-envelope"></i> Send</button>
            </div>
        </form>
    </div>
</div>