<div class="row">
    <div class="col-sm-4 col-sm-offset-4">
<?php
if (!empty($user))
{
    ?>
        <h2>Password Reset</h2>
        <p>Your password has been successfully reset, you may now use it to log in.</p>
    <?php
}
else
{
    ?>
    <h2><i class="fa fa-user-secret"></i> Password Reset</h2>
    <p>Please use the form below to reset your password.</p>
    <form role="form" action="" method="post">
        <div class="form-group">
            <input class="form-control" name="password" type="password" placeholder="New Password"/>
        </div>
        <div class="form-group">
            <input class="form-control" name="cpassword" type="password" placeholder="Confirm New Password"/>
        </div>
        <button class="btn btn-danger" type="submit">Submit <i class="fa fa-arrow-circle-o-right"></i></button>
    </form>
    <?php
}
?>
    </div>
</div>
