<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
<h2>Password Recovery</h2>
<?php
    if ($email_sent)
    {
        echo "<p>The email has been sent. Please check your email's spam folder if you did not recieve and email.</p>";
    }
    else
    {
        ?>
        <p>
            To recover your account's password, enter the email address associated with your account in the form below, and instructions to recover your password will be sent to you.
        </p>
        <form action="" method="post">
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Email Address" name="email"/>
            </div>
            <button class="btn btn-danger" type="submit">Recover Password <i class="fa fa-arrow-circle-o-right"></i></button>
        </form>
        <?php
    }
?>
        </div>
</div>