<?php

namespace DoctrineProxies\__CG__\Library\Model\Product;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Library\Model\Product\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'name', 'description', 'keywords', 'product_code', 'show_more_caption', 'base_price', 'discount_price', 'tax', 'status_override', 'status', 'base_weight', 'default_image', 'product_categories', 'skus', 'page', 'product_images', 'product_videos', 'sort_order', 'important', 'id', 'date_created', 'date_modified');
        }

        return array('__isInitialized__', 'name', 'description', 'keywords', 'product_code', 'show_more_caption', 'base_price', 'discount_price', 'tax', 'status_override', 'status', 'base_weight', 'default_image', 'product_categories', 'skus', 'page', 'product_images', 'product_videos', 'sort_order', 'important', 'id', 'date_created', 'date_modified');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function shouldShowMoreCaption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'shouldShowMoreCaption', array());

        return parent::shouldShowMoreCaption();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowMoreCaption($show_more_caption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowMoreCaption', array($show_more_caption));

        return parent::setShowMoreCaption($show_more_caption);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortOrder', array());

        return parent::getSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortOrder($sort_order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortOrder', array($sort_order));

        return parent::setSortOrder($sort_order);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductImages', array());

        return parent::getProductImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductVideos', array());

        return parent::getProductVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductVideos($product_videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductVideos', array($product_videos));

        return parent::setProductVideos($product_videos);
    }

    /**
     * {@inheritDoc}
     */
    public function setProductImages($product_images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductImages', array($product_images));

        return parent::setProductImages($product_images);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountPrice', array());

        return parent::getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountPrice($discount_price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountPrice', array($discount_price));

        return parent::setDiscountPrice($discount_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPage', array());

        return parent::getPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPage($page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPage', array($page));

        return parent::setPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkus', array());

        return parent::getSkus();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkus($skus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkus', array($skus));

        return parent::setSkus($skus);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCategories', array());

        return parent::getProductCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusOverride()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusOverride', array());

        return parent::getStatusOverride();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusOverride($status_override)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusOverride', array($status_override));

        return parent::setStatusOverride($status_override);
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCategories($product_categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCategories', array($product_categories));

        return parent::setProductCategories($product_categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function isImportant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isImportant', array());

        return parent::isImportant();
    }

    /**
     * {@inheritDoc}
     */
    public function setImportant($important)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImportant', array($important));

        return parent::setImportant($important);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', array());

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywords($keywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywords', array($keywords));

        return parent::setKeywords($keywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCode', array());

        return parent::getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCode($product_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCode', array($product_code));

        return parent::setProductCode($product_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getBasePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBasePrice', array());

        return parent::getBasePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setBasePrice($base_price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBasePrice', array($base_price));

        return parent::setBasePrice($base_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTax', array());

        return parent::getTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setTax($tax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTax', array($tax));

        return parent::setTax($tax);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseWeight', array());

        return parent::getBaseWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseWeight($base_weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseWeight', array($base_weight));

        return parent::setBaseWeight($base_weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultImage', array());

        return parent::getDefaultImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultImage($default_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultImage', array($default_image));

        return parent::setDefaultImage($default_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function addSkus($skus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSkus', array($skus));

        return parent::addSkus($skus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultSku()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultSku', array());

        return parent::getDefaultSku();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantityFromSkus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantityFromSkus', array());

        return parent::getQuantityFromSkus();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdditionalImage(\Library\Model\Media\Image $image, $sort_order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdditionalImage', array($image, $sort_order));

        return parent::addAdditionalImage($image, $sort_order);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data_array)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data_array));

        return parent::setData($data_array);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($ignore_attribute = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($ignore_attribute));

        return parent::toArray($ignore_attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function showDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'showDisplayName', array());

        return parent::showDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified($date_modified = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', array($date_modified));

        return parent::setDateModified($date_modified);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($date_created = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($date_created));

        return parent::setDateCreated($date_created);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', array());

        return parent::getDateModified();
    }

}
