<?php

namespace DoctrineProxies\__CG__\Library\Model\Shop;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Discount extends \Library\Model\Shop\Discount implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'name', 'script_name', 'dollar_hurdle', 'code', 'start_date', 'end_date', 'is_inactive', 'discount_shop_lists', 'discount_categories', 'discount_discount_actions', 'id', 'date_created', 'date_modified');
        }

        return array('__isInitialized__', 'name', 'script_name', 'dollar_hurdle', 'code', 'start_date', 'end_date', 'is_inactive', 'discount_shop_lists', 'discount_categories', 'discount_discount_actions', 'id', 'date_created', 'date_modified');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Discount $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getScriptName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScriptName', array());

        return parent::getScriptName();
    }

    /**
     * {@inheritDoc}
     */
    public function setScriptName($script_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScriptName', array($script_name));

        return parent::setScriptName($script_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountDiscountActions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountDiscountActions', array());

        return parent::getDiscountDiscountActions();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountDiscountActions($discount_discount_actions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountDiscountActions', array($discount_discount_actions));

        return parent::setDiscountDiscountActions($discount_discount_actions);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', array());

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate($start_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', array($start_date));

        return parent::setStartDate($start_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', array());

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate($end_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', array($end_date));

        return parent::setEndDate($end_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsInactive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsInactive', array());

        return parent::getIsInactive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsInactive($is_inactive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsInactive', array($is_inactive));

        return parent::setIsInactive($is_inactive);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountCategories', array());

        return parent::getDiscountCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountCategories($discount_categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountCategories', array($discount_categories));

        return parent::setDiscountCategories($discount_categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountShopLists()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountShopLists', array());

        return parent::getDiscountShopLists();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountShopLists($discount_shop_lists)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountShopLists', array($discount_shop_lists));

        return parent::setDiscountShopLists($discount_shop_lists);
    }

    /**
     * {@inheritDoc}
     */
    public function getDollarHurdle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDollarHurdle', array());

        return parent::getDollarHurdle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDollarHurdle($dollar_hurdle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDollarHurdle', array($dollar_hurdle));

        return parent::setDollarHurdle($dollar_hurdle);
    }

    /**
     * {@inheritDoc}
     */
    public function addDiscountAction(\Library\Model\Shop\DiscountAction $discount_action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiscountAction', array($discount_action));

        return parent::addDiscountAction($discount_action);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data_array)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data_array));

        return parent::setData($data_array);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($ignore_attribute = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($ignore_attribute));

        return parent::toArray($ignore_attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function showDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'showDisplayName', array());

        return parent::showDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified($date_modified = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', array($date_modified));

        return parent::setDateModified($date_modified);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($date_created = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($date_created));

        return parent::setDateCreated($date_created);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', array());

        return parent::getDateModified();
    }

}
