<?php

namespace DoctrineProxies\__CG__\Library\Model\Page;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Page extends \Library\Model\Page\Page implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'title', 'url_handle', 'page_type', 'access', 'inactive', 'keywords', 'description', 'head_scripts', 'stylesheets', 'footer_scripts', 'id', 'date_created', 'date_modified');
        }

        return array('__isInitialized__', 'title', 'url_handle', 'page_type', 'access', 'inactive', 'keywords', 'description', 'head_scripts', 'stylesheets', 'footer_scripts', 'id', 'date_created', 'date_modified');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Page $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlHandle', array());

        return parent::getUrlHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlHandle($url_handle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlHandle', array($url_handle));

        return parent::setUrlHandle($url_handle);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccess', array());

        return parent::getAccess();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccess($access)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccess', array($access));

        return parent::setAccess($access);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', array());

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywords($keywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywords', array($keywords));

        return parent::setKeywords($keywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeadScripts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeadScripts', array());

        return parent::getHeadScripts();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeadScripts($head_scripts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeadScripts', array($head_scripts));

        return parent::setHeadScripts($head_scripts);
    }

    /**
     * {@inheritDoc}
     */
    public function getStylesheets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStylesheets', array());

        return parent::getStylesheets();
    }

    /**
     * {@inheritDoc}
     */
    public function getInactive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInactive', array());

        return parent::getInactive();
    }

    /**
     * {@inheritDoc}
     */
    public function setInactive($inactive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInactive', array($inactive));

        return parent::setInactive($inactive);
    }

    /**
     * {@inheritDoc}
     */
    public function setStylesheets($stylesheets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStylesheets', array($stylesheets));

        return parent::setStylesheets($stylesheets);
    }

    /**
     * {@inheritDoc}
     */
    public function getFooterScripts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFooterScripts', array());

        return parent::getFooterScripts();
    }

    /**
     * {@inheritDoc}
     */
    public function setFooterScripts($footer_scripts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFooterScripts', array($footer_scripts));

        return parent::setFooterScripts($footer_scripts);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageType', array());

        return parent::getPageType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageType($page_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageType', array($page_type));

        return parent::setPageType($page_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullUrl', array());

        return parent::getFullUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data_array)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data_array));

        return parent::setData($data_array);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($ignore_attribute = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($ignore_attribute));

        return parent::toArray($ignore_attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function showDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'showDisplayName', array());

        return parent::showDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified($date_modified = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', array($date_modified));

        return parent::setDateModified($date_modified);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($date_created = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($date_created));

        return parent::setDateCreated($date_created);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', array());

        return parent::getDateModified();
    }

}
